name       : perl-sgmlspm
version    : '1.1'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz : 550c9245291c8df2242f7e88f7921a0f636c7eec92c644418e7d89cfea70b2bd
license    : GPL-2.0
component  : programming.perl
summary    : A perl class library for sgmls and nsgmls parsers
description: |
    A perl class library for sgmls and nsgmls parsers
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
